version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://siply:siply@db:5432/siply
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: siply
      POSTGRES_PASSWORD: siply
      POSTGRES_DB: siply
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
