name: mcMMOPlugin
version: 0.1.0
main: com.example.mcmmoplugin.McMMOPlugin
api-version: '1.21'
description: >-
  Custom mcMMO administrative helpers for quest and skill management.
authors:
  - Siply Dev Team
commands:
  mcmmoadmin:
    description: Admin commands for mcMMO integration.
    usage: /<command> <subcommand>
    permission: mmo.admin
permissions:
  mmo.admin:
    description: Grants access to all administrative mcMMO tools.
    default: op
    children:
      mmo.admin.quest: true
      mmo.admin.skills: true
  mmo.admin.quest:
    description: Allows managing mcMMO quests.
    default: op
  mmo.admin.skills:
    description: Allows managing mcMMO skill data.
    default: op
